CREATE DATABASE IF NOT EXISTS clicker_db;

USE clicker_db;

CREATE TABLE IF NOT EXISTS click (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_auto BOOLEAN DEFAULT FALSE
);
